#run neofetch
neofetch #--source ~/Pictures/ASCIIart/wolf.txt

#aliases
alias ll="ls -l"
alias la="ls -lA"
alias pupdate="sudo pacman -Syu && yay -Syu"
alias pinstall="sudo pacman -S"
alias puninstall="sudo pacman -Rns"
alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
alias ip="ip -c"
alias syncCuentas=$HOME/.scripts/cuentas.sh
alias syncDocs=$HOME/.scripts/docs.sh

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

#set the theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#import themes
export PATH=$PATH:/home/ander/.spicetify
