#run neofetch
neofetch 

#history fix
HISTFILE=~/.zsh_history
HISTSIZE=1000
SAVEHIST=1000

# Autosugestions and menu navigation
source ~/.programs/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
autoload -U compinit; compinit
zstyle ':completion:*' menu select

# Synthax highlight
source ~/.programs/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# Theme
source ~/.programs/zsh/powerlevel10k/powerlevel10k.zsh-theme

#aliases
alias ll="ls -l"
alias la="ls -lA"
alias pupdate="sudo pacman -Syu && yay -Syu"
alias pinstall="sudo pacman -S"
alias puninstall="sudo pacman -Rns"
alias ip="ip -c"
alias cuentas="bash /home/ander/.scripts/bacCuentas.sh"
alias yeet-orphans="sudo pacman -R $(pacman -Qtdq)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
