#run neofetch
neofetch #--source ~/Pictures/ASCIIart/wolf.txt

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
#  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi

#aliases
alias ll="ls -l"
alias la="ls -lA"
alias pupdate="sudo pacman -Syu && yay -Syu"
alias pinstall="sudo pacman -S"
alias puninstall="sudo pacman -Rns"
alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
alias ip="ip -c"
alias cuentas="bash /home/ander/.scripts/bacCuentas.sh"
alias yeet-orphans="sudo pacman -R $(pacman -Qtdq)"
alias fixdns="sudo echo \"nameserver 8.8.8.8 > /etc/resolv.conf\""

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
#set the theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

#import themes
#source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme
export PATH=$PATH:/home/ander/.spicetify
#source ~/powerlevel10k/powerlevel10k.zsh-theme
